config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :projects do

    resources :burn_down_charts do
      get  'get_process', :on => :collection
      get  'get_burn_down_data', :on => :collection
    end

    resources :time_series_charts do
      get  'get_time_series_data', :on => :collection
    end

    resources :gantt_charts do
      get  'get_gantt_chart_data', :on => :collection
    end

    resources :stacked_bar_charts do
      get  'get_stacked_bar_chart_data', :on => :collection
    end

  end

end

app/controllers/burn_down_charts_controller.rb
include MyUtility
include BurnDownChartsHelper
class BurnDownChartsController < ApplicationController
  unloadable
  menu_item :redmine_chart
  before_filter :find_project, :authorize, :find_version, :set_filter, :set_master



  def index

    respond_to do |format|
      format.html{

        # プロジェクトに所属するメンバー

        @send_data = collect_graph_data

        @send_data[:member] = MyUtility.get_project_menber(@project.id, params)

        @send_data[:daily_aggs] = collect_daily_aggs

        @send_data[:day_names] = @day_names

        @js_labels = I18n.t('burn_down_charts.js')

      }
      format.zip {
=begin
        fileName_nonExt = "Aggregation_#{Date.today.strftime("%Y-%m-%d")}"

        zipData = store_data_with_encryptZip(
          Aggregation.store_allRecord_with_excelData,
          "#{fileName_nonExt}.xls",
          '1234'
        )

        send_data zipData.string, :type => 'application/zip',
                  :disposition => 'attachment',
                  :filename => "#{fileName_nonExt}.zip"
=end
        send_aggregation_send_zipFormat
      }
    end

  end

  def get_process

    subjects = Hash.new
    result = Aggregation.get_progress_each_assigned(@filter)
    Issue.where(id: result.pluck("issue_id")).pluck('id, subject').each do |v|
      subjects[v[0]] =  v[1]
    end

    render json: [{:method => 'obj_after',:value => render_to_string(partial: "burn_down_charts/index_t/process",
                                            locals: {contents: result.order("user_name"), subject: subjects, cells: params[:cells]} )}]

  end

  def get_burn_down_data

    data = collect_graph_data

    data[:member] = MyUtility.get_project_menber(@project.id, params)

    data[:daily_aggs] = collect_daily_aggs

    data[:day_names] = @day_names

    data[:render_table] = render_to_string(partial: "burn_down_charts/index_t/table",:locals => {:data => data} )
    data[:render_summary] = cell("cells/filter").(:sum, {project_id: @project.id,
                                                         params: params, filter: @filter,
                                                         member: data[:member]})
    data[:render_assigned_summary] = cell("cells/filter").(:sum_assigned, {project_id: @project.id,
                                                         params: params, filter: @filter,
                                                         member: data[:member]})

    render json: [{:method => 'done',:data => data}]

  end

private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_version
    version = Version.where("project_id = ?", @project.id)
    option = {:message => I18n.t('burn_down_charts.version_not exist')}
    render_404(option) if 0 >= version.length
  end

  def collect_graph_data
    begin

      estimated = Array.new
      atual = Array.new
      plan = Array.new
      daily_gap = Array.new

      data = Aggregation.get_aggs_each_daily(@filter)
      # データが存在しない場合は処理しない
      return {:estimated => nil, :atual => nil, :plan => nil, :daily_gap => nil} if data.length <= 0

      data.each_with_index do |v, i|
        estimated.push({date: v.today, value: v.estimated_sum})
        atual.push({date: v.today, value: v.estimated_sum - v.actual_sum})
        plan.push({date: v.today, value:v.estimated_sum - v.plan_value_sum})
        daily_gap.push(v.actual_sum - v.plan_value_sum)
      end
      start_date, due_date = Aggregation.get_both_date(@filter)

      count = 0
      ((data[data.length-1].today+1)..due_date).each_with_index do |v, i|
        next if v.wday == 0 or v.wday == 6 or v < start_date
        count += 1
      end

      r_average = plan[plan.length-1][:value].quo(count)

      ((data[data.length-1].today+1)..due_date).each_with_index do |v, i|
        estimated.push({date: v, value: data[data.length-1].estimated_sum})
        if v.wday == 0 or v.wday == 6 or v < start_date
          plan.push({date: v, value:plan[plan.length-1][:value]})
        else
          plan.push({date: v, value:plan[plan.length-1][:value] - r_average})
        end
      end

      # planの最後は0
      plan[plan.length-1]['value'] = 0

      return {:estimated => estimated, :atual => atual, :plan => plan, :daily_gap => daily_gap}
    rescue => e
      logger.error($@)
      logger.error(e.message)

      return {:estimated => nil, :atual => nil, :plan => nil, :daily_gap => nil}
    end

  end

  def collect_daily_aggs

    array = Array.new
    daily_aggs =  Array.new

    group_by_today = Aggregation.get_aggs_each_daily_assigned(@filter)

    today = group_by_today[0].today if group_by_today.length > 0

    group_by_today.each_with_index do |v, index|

      if today != v.today
        daily_aggs.push(array)
        array = Array.new
        today = v.today
      end

      array.push({name: v.name, sum: v.progress})

    end

    if group_by_today.length > 0
      daily_aggs.push(array)
    end

    return daily_aggs

  end

  def set_filter
    @filter = MyUtility.set_filter(params, @project.id)
  end

  def set_master
    @day_names = [
        I18n.t('burn_down_charts.sun'),
        I18n.t('burn_down_charts.mon'),
        I18n.t('burn_down_charts.tue'),
        I18n.t('burn_down_charts.wed'),
        I18n.t('burn_down_charts.thu'),
        I18n.t('burn_down_charts.fri'),
        I18n.t('burn_down_charts.sat')
    ]
  end

  def store_data_with_encryptZip(data, filename, encrypt, encoding=Encoding::CP932)
    require 'zip'
    Zip::OutputStream.write_buffer((StringIO.new '').set_encoding(encoding),
                                   Zip::TraditionalEncrypter.new(encrypt)) do |out|
      out.put_next_entry(filename.encode(encoding))
      out.write data.string
    end
  end

  def send_aggregation_send_zipFormat
    fileName_nonExt = "Aggregation_#{Date.today.strftime("%Y-%m-%d")}"

    zipData = store_data_with_encryptZip(
      Aggregation.store_allRecord_with_excelData,
      "#{fileName_nonExt}.xls",
      '1234'
    )

    send_data zipData.string, :type => 'application/zip',
              :disposition => 'attachment',
              :filename => "#{fileName_nonExt}.zip"
  end

end

app/helpers/burn_down_charts_helper.rb
module BurnDownChartsHelper

  def get_num_color(n)
    color = ""
    if 0 <= n
      color = 'surplus'
    else
      color = 'deficit'
    end
  end

  def get_n_color_of_assignend(n)
    color = ""
    if 0 < n
      color = 'surplus'
    else
      color = 'deficit'
    end
  end

  def uname_opacity(v,flg)
    if 1 == flg
      "<span style='opacity: 0'>" + ERB::Util.html_escape(v) + '</span>'
    else
      "<span>" + ERB::Util.html_escape(v) + '</span>'
    end
  end

end

app/views/burn_down_charts/index.html.erb
<%= stylesheet_link_tag "common/common", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "burn_down_charts/index", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery-ui.min", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>
<%= javascript_include_tag "d3.v4.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery-3.1.0.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "common/common", :plugin => "redmine_chart" %>
<%= javascript_include_tag "burn_down_charts/index", :plugin => "redmine_chart" %>
<%= javascript_include_tag "burn_down_charts/burn_down_chart", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>

<h2 class="redmine_chart"><%= t('.view_h2') %></h2>

<%= render(partial: "layouts/change_view",:locals => {
    :index => project_burn_down_charts_path,
    :project_identifier => @project.identifier
} ) %>

<%= link_to 'CSV形式でダウンロード', project_burn_down_charts_path(format: 'zip') %>

<%= cell("cells/filter").(:filter, project_id: @project.id) %>

<%= cell("cells/filter").(:sum, {project_id: @project.id,
                                 params: params, filter: @filter,
                                 member: @send_data[:member]}) %>

<%= cell("cells/filter").(:sum_assigned, {project_id: @project.id,
                                 params: params, filter: @filter,
                                 member: @send_data[:member]}) %>


<svg id="MyGraph" class="svg_main"></svg>

<div id='daily_act_view' class="autoscroll" style="width: 100%">
  <%= render(partial: "burn_down_charts/index_t/table",
             :locals => {:data => @send_data} ) %>
</div>

<script>
  var $p = {};

  $p.label = <%== JSON.generate(@js_labels) %>;

  $p.index = new IndexController({
    burndown: new BurnDownsChart({
      o_dset1: <%== @send_data[:estimated].to_json %>,
      o_dset2: <%== @send_data[:atual].to_json %>,
      o_dset3: <%== @send_data[:plan].to_json %>}),
    url: '<%= get_process_project_burn_down_charts_path %>',
    url2: '<%= get_burn_down_data_project_burn_down_charts_path %>'
  });

  window.onload = function () {
    setTimeout((function(){
      // コンテンツの表示
      $('div#content').css('visibility', 'visible');
    }) , 50);
  };

</script>