config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :projects do

    resources :burn_down_charts do
      get  'get_process', :on => :collection
      get  'get_burn_down_data', :on => :collection
    end

    resources :time_series_charts do
      get  'get_time_series_data', :on => :collection
    end

    resources :gantt_charts do
      get  'get_gantt_chart_data', :on => :collection
    end

    resources :stacked_bar_charts do
      get  'get_stacked_bar_chart_data', :on => :collection
    end

  end

end

app/controllers/gantt_charts_controller.rb
include MyUtility
include GanttChartsHelper
class GanttChartsController < ApplicationController
  unloadable
  menu_item :redmine_chart
  before_filter :find_project, :authorize, :find_version, :set_filter

  def index

    @chart_data = collect_gantt_chart_data

  end

  def get_gantt_chart_data

    send = Hash.new

    send[:data] = collect_gantt_chart_data

    member = MyUtility.get_project_menber(@project.id, params)

    send[:render_summary] = cell("cells/filter").(:sum, {project_id: @project.id,
                                                         params: params, filter: @filter,
                                                         member: member})

    render json: [{:method => 'done',:data => send}]

  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_version
    version = Version.where("project_id = ?", @project.id)
    option = {:message => I18n.t('burn_down_charts.version_not exist')}
    render_404(option) if 0 >= version.length
  end

  def collect_gantt_chart_data

    pos = 0
    chart_data = Array.new
    is_closed = IssueStatus.where('is_closed > 0').pluck('id')
    max = Date.parse('2000-01-01')
    min = Date.parse('2099-01-01')

    RedmineChartIssue.get_progress_total_rate(@filter).each_with_index do |v,i|
      # 開始日と終了日がない場合はそれぞれ初期値を投入
      v.start_date ||= Date.today
      v.due_date ||= v.start_date + 10
      v.estimated ||= 0
      v.act_rate ||= 0

      # 残日数
      r_day = v.due_date - (v.start_date-1)
      average = v.estimated.quo(r_day.to_i)
      act = v.act_rate.quo(average.to_f)

      chart_data[i] = [Hash.new,Hash.new]
      chart_data[i][0][:href] = nil
      chart_data[i][1][:href] = nil
      chart_data[i][0][:text] = "合計)" + v.estimated.round(1).to_s + "h/"
      chart_data[i][0][:text] += v.act_rate.round(1).to_s + "h/" + v.rem_rate.round(1).to_s + "h"
      chart_data[i][1][:text] = ""
      chart_data[i][0][:data] = r_day.to_i*24
      chart_data[i][1][:data] = act.to_f*24
      chart_data[i][0][:pos] =  pos
      chart_data[i][1][:pos] =  pos
      chart_data[i][0][:color] =  "#DFDFDF"
      chart_data[i][1][:color] =  gantt_color(v, is_closed)
      chart_data[i][0][:date] =  v.start_date
      chart_data[i][1][:date] =  v.start_date
      pos +=30
    end

    RedmineChartIssue.get_task_progress_rate(@filter).each_with_index do |v,i|

      # 開始日と終了日がない場合はそれぞれ初期値を投入
      v.start_date ||= Date.today
      v.due_date ||= v.start_date + 10

      # 残日数
      r_day = v.due_date - (v.start_date-1)
      average = v.estimated.quo(r_day.to_i)
      act = v.act_rate.quo(average.to_f)

      chart_data.push([Hash.new,Hash.new])
      aP = chart_data.length-1
      chart_data[aP][0][:href] = issue_path(v.id)
      chart_data[aP][1][:href] = issue_path(v.id)
      chart_data[aP][0][:text] = v.name + ")" + v.subject.to_s
      chart_data[aP][1][:text] = ""
      chart_data[aP][0][:data] = (r_day*24).to_i
      chart_data[aP][1][:data] = (act*24).to_f
      chart_data[aP][0][:pos] =  pos
      chart_data[aP][1][:pos] =  pos
      chart_data[aP][0][:color] =  "#DFDFDF"
      chart_data[aP][1][:color] =  gantt_color(v, is_closed)
      chart_data[aP][0][:date] =  v.start_date
      chart_data[aP][1][:date] =  v.start_date
      pos +=30

      min = v.start_date if min > v.start_date
      max = v.due_date if max < v.due_date

    end
    return {:data => chart_data, :start_date => min, :due_date => (max+1)}
  end

  def set_filter
    @filter = MyUtility.set_filter(params, @project.id)
  end

end

app/helpers/gantt_charts_helper.rb
module GanttChartsHelper

  def gantt_color(v, is_closed)

    r_day = v.due_date - (v.start_date-1)
    average = v.estimated.quo(r_day)
    if v.due_date < Date.today
      now = r_day
    else
      now = Date.today - v.start_date
    end

    if  is_closed.find {|n| n.to_i == v.status_id.to_i}
      '#89d6e2' # is_closed
    elsif v.act_rate < now*average
      '#FF727B' # delayed
    else
      '#a5e899' # as scheduled
    end

  end
end

app/views/gantt_charts/index.html.erb
<%= stylesheet_link_tag "common/common", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "gantt_charts/index", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery-ui.min", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>
<%= javascript_include_tag "d3.v4.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery-3.1.0.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "common/common", :plugin => "redmine_chart" %>
<%= javascript_include_tag "gantt_charts/index", :plugin => "redmine_chart" %>
<%= javascript_include_tag "gantt_charts/gantt_chart", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>

<h2 class="redmine_chart"><%= t('.view_h2') %></h2>

<%= render(partial: "layouts/change_view",:locals => {
    :index => project_gantt_charts_path,
    :project_identifier => @project.identifier
} ) %>

<%= cell("cells/filter").(:filter, project_id: @project.id) %>

<%= cell("cells/filter").(:sum, {project_id: @project.id,
                                 params: params, filter: @filter,
                                 member: @member}) %>

<svg id='gantchart' class="svg_main"></svg>
<div class="div_svg_footer">
  <svg id='svg_footer' class="svg_footer"></svg>
</div>

<script>
  var $p = {};
  $p.index = new IndexController({
    chart: new GanttChart(<%== JSON.generate(@chart_data) %>),
    url: '<%= get_gantt_chart_data_project_gantt_charts_path %>'
  });

  window.onload = function () {
    setTimeout((function(){
      // コンテンツの表示
      $('div#content').css('visibility', 'visible');
    }) , 50);
  };

</script>