config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  resources :projects do

    resources :burn_down_charts do
      get  'get_process', :on => :collection
      get  'get_burn_down_data', :on => :collection
    end

    resources :time_series_charts do
      get  'get_time_series_data', :on => :collection
    end

    resources :gantt_charts do
      get  'get_gantt_chart_data', :on => :collection
    end

    resources :stacked_bar_charts do
      get  'get_stacked_bar_chart_data', :on => :collection
    end

  end

end

app/controllers/time_series_charts_controller.rb
include MyUtility
include TimeSeriesChartsHelper
class TimeSeriesChartsController < ApplicationController
  unloadable
  menu_item :redmine_chart
  before_filter :find_project, :authorize, :set_filter

  def index

    params[:f_view_point] ||= 'assigned_to'
    params[:f_method] ||= "sum_act_value"

    @chart_data = collect_graph_data(params)

    # プロジェクトに所属するメンバー
    @member = MyUtility.get_project_menber(@project.id, params)

  end

  def get_time_series_data

    send = Hash.new

    send[:data] = collect_graph_data(params)

    member = MyUtility.get_project_menber(@project.id, params)

    send[:render_summary] = cell("cells/filter").(:sum, {project_id: @project.id,
                                                         params: params, filter: @filter,
                                                         member: member})

    render json: [{:method => 'done',:data => send}]

  end

private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def collect_graph_data(params)

    sum = 0
    count = 0
    chart_data = Array.new

    data = Aggregation.get_sum_each_daily_data(@filter, get_map(params[:f_view_point], params[:f_method]))

    data[:data].each_with_index do |v,i|

      chart_data[count] ||= Hash.new
      chart_data[count]['date'] ||= v[0]
      chart_data[count][v[1]] = v[2].to_i

      if data[:data].length == i+1 || data[:data][i+1][0]  != v[0]

        tmp_sum = 0
        data[:keys].each do |v|
          if chart_data[count][v].blank?
            chart_data[count][v] = 0
          end
          tmp_sum += chart_data[count][v]
        end
        sum = tmp_sum if sum < tmp_sum
        count += 1

      end

    end

    return {:data => chart_data, :keys => data[:keys], :sum => sum}

  end

  def set_filter
    @filter = MyUtility.set_filter(params, @project.id)
  end

  def get_map(view, method)

    result = nil
    method_map = Hash.new
    unClosed_id = IssueStatus.where(is_closed: 0).pluck("id").join(",")

    view_map = {
        'assigned_to' => {:joins => :assigned_to, :pluck => "concat(lastname,' ',firstname)"},
        'tracker' => {:joins => :tracker, :pluck => "name"},
        'status' => {:joins => :status, :pluck => "name"},
        'priority' => {:joins => :priority, :pluck => "name"},
        'category' => {:joins => :category, :pluck => "name"},
        'fixed_version' => {:joins => :fixed_version, :pluck => "name"}
    }

    if view_map[view].present?

      method_map["sum_act_value"] = {:query => "sum(aggregations.act_value)"}
      method_map["sum_rem_act_value"] = {:query => "sum(aggregations.estimated_hours) - sum(aggregations.act_value)"}
      method_map["count_act_value"] = {:query => "sum(case when aggregations.act_value > 0 then 1 else 0 end)"}
      method_map["count_rem_act_value"] = {:query => "sum(case when aggregations.status_id in (#{unClosed_id}) then 1 else 0 end)"}

      result = {:view => view_map[view], :method => method_map[method]} if method_map[method].present?

    end

    return result

  end

end

app/helpers/time_series_charts_helper.rb
module TimeSeriesChartsHelper
end

app/views/time_series_charts/index.html.erb
<%= stylesheet_link_tag "common/common", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "time_series_charts/index", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery-ui.min", :plugin => "redmine_chart" %>
<%= stylesheet_link_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>
<%= javascript_include_tag "d3.v4.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery-3.1.0.min", :plugin => "redmine_chart" %>
<%= javascript_include_tag "common/common", :plugin => "redmine_chart" %>
<%= javascript_include_tag "time_series_charts/index", :plugin => "redmine_chart" %>
<%= javascript_include_tag "time_series_charts/time_series_chart", :plugin => "redmine_chart" %>
<%= javascript_include_tag "jquery.MultiSelectFilter", :plugin => "redmine_chart" %>

<h2 class="redmine_chart"><%= t('.view_h2') %></h2>

<%= render(partial: "layouts/change_view",:locals => {
    :index => project_time_series_charts_path,
    :project_identifier => @project.identifier
} ) %>

<%= cell("cells/filter").(:filter, project_id: @project.id) %>

<%= cell("cells/filter").(:timeSeries_filter) %>

<%= cell("cells/filter").(:sum, {project_id: @project.id,
                                 params: params, filter: @filter,
                                 member: @member}) %>

<svg id="MyGraph" class="svg_main"></svg>

<script>
  var $p = {};
  $p.index = new IndexController({
    chart: new TimeSeriesChart(<%== JSON.generate(@chart_data) %>),
    url: '<%= get_time_series_data_project_time_series_charts_path %>'
  });

  window.onload = function () {
    setTimeout((function(){
      // コンテンツの表示
      $('div#content').css('visibility', 'visible');
    }) , 50);
  };

</script>